name: rongowai
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.14
  - ipykernel
  - xarray
  - rioxarray
  - netcdf4
  - geopandas
  - geodatasets
  - matplotlib
  - pandas
  - geopandas
  - netCDF4
  - leafmap
  - pydeck
  - tqdm
  - numpy
  - shapely
  - geopy
  - scipy
  - itables
  - lonboard
  - matplotlib
  - ipywidgets
  - openpyxl
  - dask
  